name: "Interface Bug Report"
description: Report a visual or interaction bug in the user interface
title: "my bug"
type: bug
projects:
  - quintel/17
labels: ["ui"]
assignees: []
projects_fields:
  quintel/17:
    Urgency: urgency
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### Enter issue information
        Thanks for reporting a UI issue! Please fill out the details below so we can fix it quickly.

  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "Briefly describe what's wrong (e.g. 'Values misaligned on dashboard')."
      placeholder: "Short and clear summary"

  - type: dropdown
    id: urgency
    attributes:
      label: "Urgency / Impact"
      description: "How severe is the issue?"
      options:
        - Nice to Have
        - Low
        - Medium
        - High
        - Critical
      default: Low

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What did you expect to happen? What actually happened?"
      placeholder: |
        Example:
        - Expected: Button stays in place on scroll
        - Actual: Button overlaps with the footer when scrolling
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Please list the steps so we can see the issue ourselves."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Optional context

  - type: input
    id: url
    attributes:
      label: "URL or Screen"
      description: "Where did you notice this issue? (e.g. specific page, modal, or component)"
      placeholder: "https://my.energytransitionmodel.com"

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If possible, add a screenshot or video to help visualize the issue."
      placeholder: "Drag and drop or paste your image here"

  - type: textarea
    id: other
    attributes:
      label: "Anything else? (optional)"
      description: "Any other useful information"
      placeholder: "e.g., might be related to issue xxx"

  - type: markdown
    attributes:
      value: |
        Thanks! The more info you include, the faster we can fix it!
